//
// Generated by JTB 1.3.2
//

package IR.syntaxtree;

import IR.visitor.GJNoArguVisitor;
import IR.visitor.GJVisitor;
import IR.visitor.GJVoidVisitor;
import IR.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> ( Instruction() )*
 * f1 -> "return"
 * f2 -> Identifier()
 */
public class Block implements Node {
   public NodeListOptional f0;
   public NodeToken f1;
   public Identifier f2;

   public Block(NodeListOptional n0, NodeToken n1, Identifier n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Block(NodeListOptional n0, Identifier n1) {
      f0 = n0;
      f1 = new NodeToken("return");
      f2 = n1;
   }

   public void accept(Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

