//
// Generated by JTB 1.3.2
//

package IR.syntaxtree;

import IR.visitor.GJNoArguVisitor;
import IR.visitor.GJVisitor;
import IR.visitor.GJVoidVisitor;
import IR.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> Identifier()
 * f1 -> "="
 * f2 -> "@"
 * f3 -> FunctionName()
 */
public class SetFuncName implements Node {
   public Identifier f0;
   public NodeToken f1;
   public NodeToken f2;
   public FunctionName f3;

   public SetFuncName(Identifier n0, NodeToken n1, NodeToken n2, FunctionName n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public SetFuncName(Identifier n0, FunctionName n1) {
      f0 = n0;
      f1 = new NodeToken("=");
      f2 = new NodeToken("@");
      f3 = n1;
   }

   public void accept(Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

