//
// Generated by JTB 1.3.2
//

package cs132.IR.syntaxtree;

/**
 * Grammar production:
 * f0 -> "error"
 * f1 -> "("
 * f2 -> StringLiteral()
 * f3 -> ")"
 */
public class ErrorMessage implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public StringLiteral f2;
   public NodeToken f3;

   public ErrorMessage(NodeToken n0, NodeToken n1, StringLiteral n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public ErrorMessage(StringLiteral n0) {
      f0 = new NodeToken("error");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
   }

   public void accept(cs132.IR.visitor.Visitor v) {
      v.visit(this);
   }
public <R,A> R accept(cs132.IR.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
public <R> R accept(cs132.IR.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }

public <A> void accept(cs132.IR.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }

}

