//
// Generated by JTB 1.3.2
//

package cs132.IR.syntaxtree;

/**
 * Grammar production:
 * f0 -> "["
 * f1 -> Identifier()
 * f2 -> "+"
 * f3 -> IntegerLiteral()
 * f4 -> "]"
 * f5 -> "="
 * f6 -> Identifier()
 */
public class Store implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeToken f2;
   public IntegerLiteral f3;
   public NodeToken f4;
   public NodeToken f5;
   public Identifier f6;

   public Store(NodeToken n0, Identifier n1, NodeToken n2, IntegerLiteral n3, NodeToken n4, NodeToken n5, Identifier n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public Store(Identifier n0, IntegerLiteral n1, Identifier n2) {
      f0 = new NodeToken("[");
      f1 = n0;
      f2 = new NodeToken("+");
      f3 = n1;
      f4 = new NodeToken("]");
      f5 = new NodeToken("=");
      f6 = n2;
   }

   public void accept(cs132.IR.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(cs132.IR.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(cs132.IR.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(cs132.IR.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

